pipeline {
    agent {
        label "jenkins-agent"
    }
    tools {
        go 'go1.23.1'
    }
    environment {
        APP_NAME = "gopatungan-backend"
        RELEASE = "1.0.0"
        DOCKER_USER = "ardidafa"
        DOCKER_PASS = 'dockerhub'
        IMAGE_NAME = "${DOCKER_USER}/${APP_NAME}"
        IMAGE_TAG = "${RELEASE}-${BUILD_NUMBER}"
        SONAR_TOKEN = credentials('user-sonarqube-token')
    }
    stages {
        stage("Cleanup Workspace") {
            steps {
                cleanWs()
            }
        }

        stage("Checkout from SCM") {
            steps {
                git branch: 'main', credentialsId: 'github', url: 'https://github.com/mdafaardiansyah/backend-gopatungan.git'
            }
        }

        stage("Build Application") {
            steps {
                sh 'go mod tidy' // Pastikan modul Go mutakhir
                sh 'go build -o gopatungan-backend ./cmd/gopatungan' // Membangun aplikasi Go
            }
        }
        //         stage("Test Application") {
        //             steps {
        //                 sh 'go test ./...' // Run Go unit tests
        //             }
        //         }

        stage('SonarQube Analysis') {
            environment {
                scannerHome = tool 'sonarqube-scanner-latest'
            }
            steps {
                script {
                    withSonarQubeEnv(credentialsId: 'user-sonarqube-token', installationName: 'sonarqube-scanner') {
                        sh """
                        ${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=gopatungan-backend \
                        -Dsonar.sources=. \
                        -Dsonar.login=${SONAR_TOKEN}
                        """
                    }
                }
            }
        }


        stage("Quality Gate") {
            steps {
                script {
                    waitForQualityGate abortPipeline: false, credentialsId: 'user-sonarqube-token'
                }
            }
        }

        stage("Build & Push Docker Image") {
            steps {
                script {
                    docker.withRegistry('', DOCKER_PASS) {
                        docker_image = docker.build("${IMAGE_NAME}", "-f build/Dockerfile .")
                    }
                    docker.withRegistry('', DOCKER_PASS) {
                        docker_image.push("${IMAGE_TAG}")
                        docker_image.push('latest')
                    }
                }
            }
        }
    }

    post {
        success {
            echo "Build succeeded!"
        }
        failure {
            echo "Build failed!"
        }
    }
}



