pipeline {
    agent {
        label "jenkins-agent"
    }
    tools {
        go 'go1.23.1'
    }
    environment {
        APP_NAME = "gopatungan-backend"
        RELEASE = "1.0.0"
        DOCKER_USER = "ardidafa"
        DOCKER_CREDS = credentials('dockerhub')
        IMAGE_NAME = "${DOCKER_USER}/${APP_NAME}"
        IMAGE_TAG = "${RELEASE}-${BUILD_NUMBER}"
        SONAR_TOKEN = credentials('user-sonarqube-token')
        VPS_SERVER = "user@your_vps_ip"
        VPS_DIR = "/path/to/gopatungan"
    }
    stages {
        stage("Cleanup Workspace") {
            steps {
                cleanWs()
            }
        }

        stage("Checkout from SCM") {
            steps {
                git branch: 'main', credentialsId: 'github', url: 'https://github.com/mdafaardiansyah/backend-gopatungan.git'
            }
        }

        stage("Build Application") {
            steps {
                sh 'go mod tidy'
                sh 'go build -o gopatungan-backend ./cmd/gopatungan'
            }
        }

        stage("Run Tests") {
            steps {
                sh 'go test ./... -v -cover'
            }
        }

        stage('SonarQube Analysis') {
            environment {
                scannerHome = tool 'sonarqube-scanner-latest'
            }
            steps {
                withSonarQubeEnv(credentialsId: 'user-sonarqube-token', installationName: 'sonarqube-scanner') {
                    sh """
                    ${scannerHome}/bin/sonar-scanner \
                    -Dsonar.projectKey=gopatungan-backend \
                    -Dsonar.sources=. \
                    -Dsonar.go.coverage.reportPaths=coverage.out \
                    -Dsonar.login=${SONAR_TOKEN}
                    """
                }
            }
        }

        stage("Quality Gate") {
            steps {
                timeout(time: 1, unit: 'HOURS') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage("Build & Push Docker Image") {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
                        def customImage = docker.build("${IMAGE_NAME}:${IMAGE_TAG}", "-f build/Dockerfile .")
                        customImage.push()
                        customImage.push('latest')
                    }
                }
            }
        }

        stage('Deploy to VPS') {
            steps {
                script {
                    sshagent(credentials: ['vps-ssh-key']) {
                        sh """
                            ssh ${VPS_SERVER} '
                                cd ${VPS_DIR}/build
                                docker-compose pull
                                docker-compose up -d --force-recreate
                            '
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            discordSend (
                webhookURL: credentials('discord-webhook'),
                title: "Deployment Successful",
                description: "${env.JOB_NAME} ${env.BUILD_NUMBER}",
                footer: 'Build berhasil!', // Menambahkan footer
                link: env.BUILD_URL, // Menambahkan link ke build
                result: currentBuild.currentResult // Menambahkan status build
            )
        }
        failure {
            discordSend (
                webhookURL: credentials('discord-webhook'),
                title: "Deployment Failed",
                description: "${env.JOB_NAME} ${env.BUILD_NUMBER}",
                footer: 'Build gagal!',
                link: env.BUILD_URL,
                result: currentBuild.currentResult
            )
        }
    }
}